import Navbar from "@/components/Navbar";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import { Inter } from "next/font/google";
require('dotenv').config();


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#b8feff] ">
      <body className={inter.className}>
      <NextTopLoader
          color="#0000FF"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />

        <div className="max-w-3xl mx-auto p-4 bg-[#a7dcdd] shadow-xl m-5 rounded-lg">

          <Navbar />

          <div className="mt-8">

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
