import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
require('dotenv').config();


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#b8feff] ">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4 bg-[#a7dcdd] shadow-xl m-5 rounded-lg">

          {/* <Navbar /> */}

          <div className="mt-8">

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
